name: C CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: clean
        run: make clean
      - name: compile
        run: make
      - name: Run bash script
        run: ./finder.sh
        shell: bash
